### ISSUE TITLE
MVP Roadmap and estimation

### ISSUE THREAD

**Issue by justinbmeyer** [bitovi/optimizely-as-code#1]
Goal:

- Document what would need to be done to produce a semi-viable opens source project
   - Someone "off the street" could use it
   - Someone "off the street" could find it
- Do it

## Short-term Roadmap

> :eyes: are needed for MVP.
> Top-level checkboxes are checked when at MVP, even if sub-items exist.

- [ ] Optimizely Research
  - If not :eyes:, then may not be actually usable on a new project.
  - [ ] What's their new experiment model?
  - [ ] Integrate new experiment model
- [ ] Rework Schemas
  - may change due to "new experiment model" above
  - [ ] features
  - [ ] events?
  - [ ] experiments?
- [x] CLI
  - [x] `sync` command using legacy code :eyes:
  - [ ] `push-features` command
    - may change due to "new experiment model" above
    - new code to push features with better schemas
  - [ ] `validate-experiments` command?
    - may change due to "new experiment model" above
    - Do we need to store experiments in the repo? Ideally, no. But can validate them.
  - [ ] `push-events` command?
    - may change due to "new experiment model" above
    - What do "events" actually do?
    - may not even be necessary
- [ ] Plain FE integration
  - may not be possible in :eyes:, due to "new experiment model"
  - [ ] initial passthrough
  - [ ] typings
  - [ ] fixtures: defaults
  - [ ] fixtures: overridable
- [x] React integration
  - [x] initial passthrough :eyes:
  - [ ] typings
  - [ ] fixtures: defaults
  - [ ] fixtures: overridable
- [x] Error handling
  - [x] initial: not silent errors :eyes:
  - [ ] fully detailed errors with suggestions
- [ ] Documentation
  - [x] Installation :eyes:
  - [ ] Optimizely Setup :eyes:
  - [x] CLI Usage :eyes:
  - [x] React Usage :eyes:
  - [ ] Defining data :eyes:
- [ ] Testing
  - [ ] Syncing logic
  - [ ] React integration
- [ ] Review usability
- [ ] Search term review

**Comment by ConnorGraham** [comment]
## Estimates

Total: 3.5 days

### Interface (0.5d)
* Build cli interface that accepts
  * path to json files
  * optimizely project id (or ENV var)
  * optimizely api key (or ENV var)
  * dry run mode
* Improve general logging 

### Error handling (0.5d)
* Return a useful error message on non 200 api calls

### Documentation (0.5d)
* Tool installation
* Usage
* Setting up Optimizely account
* json schema

### Testing (1d)
Create tests for
* delta logic
* compatibility with optimizely schema

### Peer Review and SEO (1d)
Get a random Bitovian to set up and use the tool with 0 guidance. In the meantime, research repo tagging and name to enable people find us.
